name: Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:

  build-push-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-and-push
        name: build and push
        with:
          image-name: "preservation-api"
          dockerfile: "./Preservation.API/Dockerfile"
          context: "LeedsExperiment"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-and-push
        with:
          image-name: "dashboard"      
          dockerfile: ./Dashboard/Dockerfile
          context: LeedsExperiment/
          github-token: ${{ secrets.GITHUB_TOKEN }}

 