name: Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:

  build-push-storage-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-and-push
        name: build and push
        with:
          image-name: "Storage-API"
          dockerfile: "./LeedsExperiment/Storage.API/Dockerfile"
          context: "./LeedsExperiment/"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-preservation-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-and-push
        name: build and push
        with:
          image-name: "Preservation-API"
          dockerfile: "./LeedsExperiment/Preservation.API/Dockerfile"
          context: "./LeedsExperiment/"
          github-token: ${{ secrets.GITHUB_TOKEN }}  

  build-push-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-and-push
        with:
          image-name: "dashboard"      
          dockerfile: "./LeedsExperiment/Dashboard/Dockerfile"
          context: "./LeedsExperiment/"
          github-token: ${{ secrets.GITHUB_TOKEN }}

 